version: '3'

services:
  frontend:
    build: similar-clothes-frontend
    restart: always
    ports:
      - 80:8501
    depends_on:
      - backend
    volumes:
      - ~/data:/data

  backend:
    build: similar-clothes-backend
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - qdrant

  qdrant:
    image: "generall/qdrant"
    restart: always
    ports:
      - 6333:6333
    volumes:
      - ~/storage:/qdrant/storage
