version: '3'

services:
  frontend:
    build: similar-clothes-frontend
    ports:
      - 80:8501
    depends_on:
      - backend
    volumes:
      - ~/data:/data
    # networks:
            # - docker_network

  backend:
    build: similar-clothes-backend
    ports:
      - 8080:8080
    depends_on:
      - qdrant
        # networks:
        #- docker_network

  qdrant:
    image: "generall/qdrant"
    ports:
      - 6333:6333
    volumes:
      - ~/storage:/qdrant/storage
        #networks:
        #- docker_network

        #networks:
        #docker_network:
        #driver: bridge
